### ISSUE TITLE
EPIC: As a potential investor or Partner in Tonomy-ID I want to see the software being used so that I get a better sense that this software is realiable

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/Tonomy-ID-Management#1]
**Description:**

- What is the purpose/reason for this task?

It is an epic for both marketing, Prototyping and parterships 

Definition of Done:

- A partner onboarded
- Partners have given reviews and they are recorded on the website
- Some marketing is done about how they are using the product
- The benefits of tonomy are clearly captured and 

Tasks can include:
- Informing Chefchain about our progress
- Helping Chefchain with demo'ing our software
- Helping partners Demo

**Comment by theblockstalk** [comment]
@kamitor please change this to an epic
