### ISSUE TITLE
Add new storage Telos UK node

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#106]
One of our volumes has been alerting for a while on storage usage. We've got them set to alert at 75%. It's creeping up very slowly, so it's not really urgent but if you want me to join somebody online and share a screen as we run through increasingly the storage together then that's fine with me.

DOD:
- new storage is expanded by 25%

**Comment by kamitor** [comment]
@Rebal67 Says it will be done on monday *grin*
