### ISSUE TITLE
Prepare Sprint Demo presentation

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#109]
Definition of done

- [ ] collect information from teammates:
- what they will demo
- what challenges and learnings they made
- [ ] collate into slides ready for the review meeting on Tuesday. @Rebal67  has a good template

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFbHrUCuiw/dstn1TBLJl77Vp2WDQr5hw/edit

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFbITarupI/sxJLvpIES6VOvPXlZpcSVw/edit?utm_content=DAFbITarupI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by theblockstalk** [comment]
SprintSprint demo was done yesterday

**Comment by theblockstalk** [comment]
SprintSprint demo was done yesterday
