### ISSUE TITLE
Send to Marketing an update of the development process - show what we have already created

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#11]
This is so that marketing team can use it to create content

Definition of done

- [x] Information is sent to the marketing team that shows the current state of development of Tonomy ID
- [x] this information includes the most visual and marketable content that we can create with the current state of the application, This can also include information about how the app works and why this is technically innovative and/or helps businesses

**Comment by aymenae** [comment]
https://tonomyfoundation.rocket.chat/channel/Marketing?msg=iEJD9MhT5bpZqCksn
