### ISSUE TITLE
Switch between apps in ecosystem - research

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#113]
As a user on a Tonomy App I've signed into
I can easily Find other Tonomy Core Apps, or Tonomy Apps that I have previously used and switch to it
So that I can use the Tonomy Apps easily and don't need to worry about finding apps I previously used

Acceptance criteria

- [ ] research into how 2 or 3 other systems do this

See how Google does it:
https://www.loom.com/share/800e8aa658a34a53bbeff6c0f8b7f576

**Comment by MilicaSequeira** [comment]
Not really the same style like Google but similarly Microsoft 365 (office) and Adobe Cloud Studio have an app picker but opens the apps in new windows. Discord and Slack switch between workspaces. So the closest feature to what Tonomy needs would be Googles Account Picker.
