### ISSUE TITLE
centralise the design system

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#114]
Acceptance criteria:

- [ ] We have one central design system in Figma that can be used in the design in multiple apps: Tonomy ID and all our websites

To do this we need to research how to make a design system. Ideally, we can have one Figma file with the design system which can be used in other Figma files. I suggest we do a very small test for one shareable component to see how this could work before applying this to a full design system.

**Comment by MilicaSequeira** [comment]
By publishing the library the whole Team ( in this case Tonomy Foundation Team) will have access to it by going to asset library and toggling it.

**Comment by MilicaSequeira** [comment]
https://www.loom.com/share/db76eecfc39a4b5591728cc68cabec24
