### ISSUE TITLE
Non-mobile design of the Tonomy login website

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#115]
The Tonomy login website should also have a non-mobile design

Acceptance criteria

- [ ] Each screen for the Tonomy login website also has a non-mobile high-fidelity design with the same functionality

Applies to all screen in the non-mobile flow
![image.png](https://images.zenhubusercontent.com/5ea82b5959354f2b8ef14f5d/7bf24b14-e0d1-43ad-9da5-c280a70af6fd)

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5492-26513

**Comment by theblockstalk** [comment]
reviewed, see comments
