### ISSUE TITLE
Interview members of the Tonomy Foundation team about How they expect Tonomy ID to help businesses

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#12]
This content can then be used to create marketing videos

Definition of done

- [ ] Minimum three members of the foundation are interviewed and questioned about their experiences and expectations for Tonomy ID and how it will help businesses

**Comment by AnnaLotukhova** [comment]
https://docs.google.com/document/d/1Dn4WtOwAowyJpzqxFFLYBoxX1l5MthNxEGMphgW0i8s/edit - text for interview
