### ISSUE TITLE
Reach out to new potential clients in personalized ways (Sprint starting 11 April)

### ISSUE THREAD

**Issue by Caihao013** [Tonomy-Foundation/Tonomy-ID-Management#123]
As a sales and business developer, I think the automatic approaches may not be sufficient enough, so that we may need additional methods by customising the approaches.

**Definition of done**

- [x] Do the research to reach out to new potential clients by editing more customised messages manually.
- [ ] Set 5 meetings with potential clients and take notes on feedbacks each meetings.

**Comment by theblockstalk** [comment]
did not complete. now outdated
