### ISSUE TITLE
Review Tonomy ID website page and make feedback suggestions to make it convert

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#124]
Acceptance criteria

- [x] Review the staging of the website https://staging-website.tonomy.foundation/
- [x] Think of how the website can be made to more effectively convert potential clients
- [x] generate any content needed (copy), or coordinate that this is created (e.g. design)
- [x] and feedback to the feedback sheets  for these changes to be made https://docs.google.com/spreadsheets/d/19qUyRjeWYNiyWnsUPIlW_PP-1Lp3hwmi0BBBCuZTx70/edit#gid=0

**Comment by Caihao013** [comment]
Add two feedbacks about 'pricing' and 'contact' parts. https://docs.google.com/spreadsheets/d/19qUyRjeWYNiyWnsUPIlW_PP-1Lp3hwmi0BBBCuZTx70/edit#gid=0

**Comment by kamitor** [comment]
Requires research to complete;

What would a good flow be?

How do we differentiate from it now?

**Comment by kamitor** [comment]
https://docs.google.com/document/d/1XOhmTzkytsAyYc6qh265xMXlA4J7wjU_qnhHNdM0p5c/edit?usp=sharing

**Comment by kamitor** [comment]
https://webflow.com/blog/saas-website-design-examples

**Comment by kamitor** [comment]
https://www.youtube.com/watch?v=yxbV-Gvnn5g&
