### ISSUE TITLE
Social media Marketing (Sprint starting 11 April)

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID-Management#128]
Use the following: https://noteshare.space/note/cle67owpi081801pjy1kg2edr#qds7+vkaQSyLBoHHPMfk7n7UoDNMw+SLsxqLjobm6/g

- [ ] Create 2 social media posts on how they Tonomy technologies (e.g. TID or Tonomy Partipicate)

**Comment by Caihao013** [comment]
Posted 'Take back Control' and a poll with Salah's help on LinkedIn.
