### ISSUE TITLE
Run internal user testing for Tonomy App Manager

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#136]
Book and run internal user testing for the new features done in Tonomy App Manager

-  [x] Talk about the features
- [x] Gather Feedback
- [x] and book with each person.

Points allocated PER PERSON.

**Comment by MilicaSequeira** [comment]
Participants: Jack, Haseeb, Rebal, Sadia, failed attempt with Yasin.

**Comment by theblockstalk** [comment]
8 points for person running this
3 points for doing the test

**Comment by MilicaSequeira** [comment]
https://drive.google.com/drive/u/1/folders/1BgE1yS9rg4-uGDHntvxnyBNFhLwgH50g

**Comment by MilicaSequeira** [comment]
To do: 
1. Make the listed  data more visible
2. See alternative path to edit mode- 2 participant went into burger menu first
3. Label steps with that they are in creating an app
4. Make going back through steps possible
5. Add a plus on home screen so use doesnt need to scroll to end list to get to register an app
6. Get a deafult image to replace a deleted logo 
7. In home page show logo of the app with its details
8. Change delete button color to something less clickable
9. Shorten space in the delete popup
