### ISSUE TITLE
Create a general-purpose TID sales package

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#144]
Acceptance criteria

- [x] create a document with links and content that can be shared with potential clients to let them know if they want to buy TID
- [x] with link to pitch deck and other content
- [ ] looks visually appealing
- [x] professional, no errors or spelling mistakes

**Comment by kamitor** [comment]
https://noteshare.space/note/clfwdgbxb432401pj8jx4fe7b#mCyjZNepBeSyoiIdHdo/93DblVG5fMwv/UkeonFgUwc

**Comment by kamitor** [comment]
Review with Milica around general deck

**Comment by kamitor** [comment]
https://noteshare.space/note/clg10y5lb174601pjqick2jfx#dCRvaNwJ+Q7Ips1WxMV0dN14DJSFXAwi42kX5EdsyV4

**Comment by theblockstalk** [comment]
If you add this in Notion and make visually appealing we can close this off

**Comment by kamitor** [comment]
Thank you; I will add this in notion:

I've additionally made a overview sheet for the feedback:
https://docs.google.com/spreadsheets/d/1ITomObhhhHkPMFDDZFw5ZGNfDlpKiB7rtOA9QQwQNB0/edit#gid=1610441119

And will need to update the links sheet that mike created for me (thank you mike)
https://docs.google.com/spreadsheets/d/197dmlAZbYL_snlzSLWNc5Va1Iw8l7ZesEkeOCfxFADk/edit#gid=683608255

**Comment by kamitor** [comment]
https://www.notion.so/tonomy-foundation/2023-04-09-Tonomy-Overview-Package-afa5d2c910094844b232c9ccfa789f2e?pvs=4
