### ISSUE TITLE
Align on the target audience for sales and create a target list

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#153]
Acceptance criteria

- [x] meeting to share experiences of doing sales and outreach
- [x] make a list of the next target audiences for outreach

**Comment by Caihao013** [comment]
https://www.canva.com/design/DAFd7U2siHc/lOZQS_Q5x3jTqjJkPP3Gcg/edit?utm_content=DAFd7U2siHc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Meeting material.

**Comment by Caihao013** [comment]
Meeting arranged.

**Comment by kamitor** [comment]
https://docs.google.com/spreadsheets/d/1l1evbSFhGMq3wicFgUMn6cyS7O9jxithgOiaRlYjHdk/edit?usp=sharing

**Comment by kamitor** [comment]
Meeting of tomorrow

**Comment by kamitor** [comment]
https://tonomy-foundation.notion.site/2023-05-9-ActivityHub-4a250cbd85ca47f7bfe02b3aab43b960

**Comment by kamitor** [comment]
https://tonomy-foundation.notion.site/2023-05-09-Ukraine-Event-c3626591492648a4addc35423800d32f
