### ISSUE TITLE
Align on what TID product offers client as workshop

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#160]
Acceptance criteria

- [x] prepare a workshop with the following two components:
  - go through the product brochure
  - go through questions/activities to understand how they deliver value to which people
- [ ] organize a meeting to go over this

ultimate goal of the workshop:
- answer the question "what can I do when I buy TID?"

follow up will be to process this into the BD material

**Comment by theblockstalk** [comment]
Who’s it for?
What’s it for?
What is the worldview of the audience you’re seeking to reach?
What are they afraid of?     
What story will you tell? Is it true?     
What change are you seeking to make?     
How will it change their status?     
How will you reach the early adopters and neophiliacs (strong affinity for novelty)?     
Why will they tell their friends?     
What will they tell their friends?     
Where’s the network effect that will propel this forward?     
What asset are you building?     
Are you proud of it?

**Comment by kamitor** [comment]
https://noteshare.space/note/clftpzycx1534301pjvvotecdg#ORrx+KfsCv/jxajDCRB3wYKgxBxmoHWI1ZA8dqdMBCQ

**Comment by kamitor** [comment]
https://app.mural.co/invitation/mural/tonomyagileworkshop2381/1680096679935?sender=u017ccaea1c9026d6f78c9210&key=00330cd8-8d26-4d20-a2be-5b8553163add
