### ISSUE TITLE
Updated pitch deck with new story

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#162]
Acceptance criteria

- [x] updated pitch deck to show understanding of the new sales offering
- [ ] pitch to 2 technical members and get feedback
- [ ] pitch to 2 externals who can give feedback

follow up - design review, and re-record Tonomy ID video

**Comment by kamitor** [comment]
https://noteshare.space/note/clg5dkej1290501pjo0np75un#bKKWOvmnX7X+UrR+H9BzaDGElPxB370JKKybooiBF1g

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFfWih11D4/eVRAg97wYaDJR2GD3Yu5nQ/edit?utm_content=DAFfWih11D4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
