### ISSUE TITLE
Select 5 real targets for sales to approach

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#166]
Acceptance criteria

- [ ] research 5 qualified companies
- [ ] find two qualified contacts at each company
- [ ] approach the contacts and try to make a very personalized engagement
- [ ] contacts and activity should be visible in Hubspot CRM

**Comment by kamitor** [comment]
https://tonomy-foundation.notion.site/2023-05-9-ActivityHub-4a250cbd85ca47f7bfe02b3aab43b960

**Comment by kamitor** [comment]
https://tonomy-foundation.notion.site/2023-05-09-Ukraine-Event-c3626591492648a4addc35423800d32f
