### ISSUE TITLE
Tonomy Demo: See how I can send a message to any other user

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#169]
As somebody who has logged in successfully to the SSO Demo (market.com)
I can now try sending a message to another user
so that I know that this tool works and how I can implement it

Acceptance criteria

- [ ] high fidelity design made
- [ ] feedback received on high fidelity design
- [ ] feedback implemented in design

**Comment by theblockstalk** [comment]
low fidelity here
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4996-25879&t=9ldsIeD9hDGktdfh-4

**Comment by MilicaSequeira** [comment]
please review https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4996-25879&t=ViU5Xh8jEfUB2C17-4
