### ISSUE TITLE
Create/update epics for developer roadmap

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#17]
Definiton of done

- [ ] Create and update epics and assign all tasks to at least one epic
- [ ] Epics should map out the developer roadmap which matches the value proposition

epics should include:

- developer docs
- SSO design
- website design
- Login and otehr epics, including login cases
- Finish create account if not finished
- my account manager

**Comment by kamitor** [comment]
Can't do this without the BCM!
