### ISSUE TITLE
Design review of BD material

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#178]
Acceptance criteria

- [ ] Designer reviews the current pitch deck and Saas Model And Benefits and provides feedback for visual improvement
- [ ] Pitch deck updated based on feedback

Pitch deck https://www.canva.com/design/DAFfCdLI5lA/i3m7GP9q4wv_1nWuaU_hjA/edit
Saas Model and benefits https://www.canva.com/design/DAFbTtHWg_0/pCdfGOdqDIuULNHc8hcvcw/edit

**Comment by MilicaSequeira** [comment]
1. Tonomy ID Permanently gets rid of is too bussy, the images are not necessary on such a small screen. And they dont say a lot compared to the graph that disappeared in the sea of images. 
One number is red, the rest are white, choiose one and stick to it. 
The title cannot be red. Red is an alert color, your not alerting to danger.
2. The title letters are so big you cannot see the IT ALL ADDS UP. It also should have more white space between each other. 
3. It has been redone by the designer but the style doesnt math the first 3 charts. either get the designer to redo the forst 2 or keep this one in the presentatioN.

**Comment by MilicaSequeira** [comment]
Slide 3: Change concerns into attacks. Its action based.
Slide 10: move the To connect all your programs 2 arrow button presses higher so the space between title and  text match with the bottom 2 then align.
Slide 20: The grey text should be just a bit more darker to increase readability.
Slide 23: its Milica and Mihkail 
Slide 26: Move Highest Security and icon closer to the middle. the distance isnt the same as for the other 3
Slide 30. tonomy ID without the -
