### ISSUE TITLE
Re-record Tonomy ID video

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#179]
Acceptance criteria

- [ ] record general Tonomy ID story for the website < 4 minutes
- [ ] upload to Youtube

Use Tonomy I.D. v4

**Comment by kamitor** [comment]
Need help cutting down!

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFfCdLI5lA/i3m7GP9q4wv_1nWuaU_hjA/edit
https://www.canva.com/design/DAFfD3_bTO4/xhHf5mzU6zVur0OWQpmVoQ/edit?utm_content=DAFfD3_bTO4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by theblockstalk** [comment]
@Mrak1985 did this video: https://www.loom.com/share/06c42e905d4640318dc66c5b09e0fd5f
