### ISSUE TITLE
Chefchain - usability testing

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#18]
Definition of done:

- [x] Conduct usability testing someone from Chefchain
- [x] Test results are documented'
- [x] Record and Upload the Video

Requires to : 
 - [x] Follow Usability Script
- [ ] Get familiar with MAZE

**Comment by theblockstalk** [comment]
https://www.notion.so/tonomy-foundation/Usability-goals-and-script-Maze-5f50c49ef33a41baaa936f049f15bd98

**Comment by kamitor** [comment]
Setup Staging 

Setup Use Test
