### ISSUE TITLE
Create additional SCRUM reports

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#183]
Acceptance criteria

- [ ] Create the following two SCRUM reports: Burn up chart and predictability chart. for the SCRUM demo

**Comment by chetanabhardwaj** [comment]
Reply from Zenhub Technical Support : For all articles related to reporting in Zenhub, please see our Help Center articles here: ​Reports and gathering insights

You can also export your Zenhub reporting data to CSV and create your own reports outside of Zenhub.
​
