### ISSUE TITLE
Research how much each problem is worth for different clients

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#184]
Acceptance criteria

- [ ] take a few of the easiest clients
-- crypto platforms
- [ ] do some market research into how much the problems identified in the workshop are worth to the client

https://app.mural.co/t/tonomyagileworkshop2381/m/tonomyagileworkshop2381/1680096679935/c558c614901164b7ed72bea620433bb4873e42c3?invited=true&sender=u1a77810773f9fba6b57d5317

**Comment by kamitor** [comment]
https://tonomy-foundation.notion.site/2023-05-09-New-Sales-Team-3b94f1bbd7424ef9877be43dffcc55fb
