### ISSUE TITLE
Map out resources needed for sales pipeline

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#189]
Acceptance criteria
- [x] map out what resources we need to manage these processes

https://app.diagrams.net/#G1gbw-OwG4bZtkDcFwJaE_OisxIN6gggnD

Follow ups
- make recruitment ads
- interview and onboard new members
- make goals for each pipeline
- make reporting mechanisms for each pipeline

**Comment by kamitor** [comment]
https://tonomy-foundation.notion.site/2023-05-09-New-Sales-Team-3b94f1bbd7424ef9877be43dffcc55fb
