### ISSUE TITLE
Research and outreach to new potential clients (Sprint starting 8 Dec)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#19]
Definition of done

- [x] Research potential businesses that would benefit from using Tonomy ID. If possible, use the use case scenario research.
- [x] Reach out to these businesses. 5-10 personalized outreaches made. PERSONALISED
- [x] document you reach out to, when and what in the CRM

**Comment by kamitor** [comment]
Casper ![Screenshot from 2022-10-13 15-30-07.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/42647dd0-52c4-4868-a009-2ba840cab0fc)

**Comment by kamitor** [comment]
Roland

**Comment by kamitor** [comment]
Refugee stuff - fail

**Comment by kamitor** [comment]
Windesheim

**Comment by kamitor** [comment]
Techinc

**Comment by kamitor** [comment]
SOCIAL CARBON CREDITS

**Comment by kamitor** [comment]
NEW PARTNER FOLLOWUP 

Guy Aubidert Ntwari
Arthur Franse
Chef Chain

**Comment by kamitor** [comment]
Bold

**Comment by kamitor** [comment]
https://www.delitelabs.com/
https://startuphub.pl/
https://www.civstart.org/innovation-hub

**Comment by kamitor** [comment]
![image.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/23578277-f564-4f2d-923a-a7df11a5970a)

**Comment by kamitor** [comment]
Frewderique - Mrunal Grant writers

**Comment by kamitor** [comment]
https://www.linkedin.com/in/attah-paul-8a1678159/

**Comment by kamitor** [comment]
Fred van Toor
Ruud Wijlhuizen
Corne

**Comment by kamitor** [comment]
Attah

**Comment by kamitor** [comment]
Girls from govtec
Rebeka Bílik
