### ISSUE TITLE
Tonomy Demo: mockups of flows after logged in

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#191]
Acceptance criteria:
- [ ] Create a mockup showing the flows of the user in the Tonomy Demo app with the following stories
- [ ] reviewed and approved

As somebody trying out the SSO Demo
I can see what data was exchanged during the login
so that I can better understand where and how to use Tonomy ID for my own website

As somebody who has logged in successfully to the SSO Demo (market.com)
I can now try signing a verifiable credential with a medical record in it
so that I know that this tool works and how I can implement it

As somebody who has logged in successfully to the SSO Demo (market.com)
I can now try signing a blockchain transaction to buy an NFT with the key that was authorized (And also see the Github code for this - User Story 1)
so that I know that this tool works and how I can implement it

As somebody who has logged in successfully to the SSO Demo (market.com)
I can now try sending a message to another user
so that I know that this tool works and how I can implement it

**Comment by MilicaSequeira** [comment]
Review needed: https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3921%3A22926&t=4kmXEkDz0zoCxv2W-1

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4823-25801&t=OCDuTSsQ9CeAiFky-4
