### ISSUE TITLE
Mobile design of the generic error page

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#199]
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/581

Acceptance criteria
- [ ] Mobile design exists for the 404 page on the SSO website

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/NuupSK3R2ddSzSuWk7gcee/Website-error-page?type=design&node-id=224-581&t=FDtvtT6eIWH6A2Wz-4
