### ISSUE TITLE
Social media (sprint starting 11 October)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#20]
Description:

We have to create and post some material on our social just to show that we are alive more or less

Definition of done:

- [x]  Visuals are created
- [ ]  Tweets posted
- [ ]  Linkedin posted
- [ ]  Content social media document is updated

**Comment by Carrie22022** [comment]
Starting the visuals portion now, but will need access to the Twitter, LinkedIn, and Social Media documents to complete this task @theblockstalk  @kamitor

**Comment by Mrak1985** [comment]
Mike 5, Stefan 16
