### ISSUE TITLE
Establish regular meeting cadence for BD team

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#205]
As a project manager, I want to establish a regular meeting cadence for the business development team to improve collaboration and ensure team members are up-to-date on project progress, so that the team can perform more effectively and efficiently.

Acceptance Criteria:
- [x] A meeting schedule is created and communicated to the business development team.
- [x] Meeting invitations are sent out in a timely manner and include an agenda and any necessary pre-reading material.
- [x] The meeting is conducted at the scheduled time, with all team members present.
- [x] The meeting is run according to the agenda, with each team member given the opportunity to speak.
- [x] Meeting notes are taken and distributed to all team members within 24 hours of the meeting.
- [ ] Any action items are clearly documented and assigned to a specific team member for follow-up.

Definition of Done:
- [x] A regular meeting schedule has been established and communicated to the business development team.
- [x] Meeting invitations have been sent out with an agenda and any necessary pre-reading material.
- [x] All scheduled meetings have been conducted at the scheduled time with all team members present.
- [x] Each meeting has been run according to the agenda, with each team member given the opportunity to speak.
- [x] Meeting notes have been taken and distributed to all team members within 24 hours of the meeting.
- [x] Any action items have been clearly documented and assigned to a specific team member for follow-up.

https://www.notion.so/tonomy-foundation/Sales-Funnel-0934cf3be7a34c91817677011e64499f?pvs=4
https://docs.google.com/spreadsheets/d/1ITomObhhhHkPMFDDZFw5ZGNfDlpKiB7rtOA9QQwQNB0/edit#gid=1902629582
https://www.notion.so/tonomy-foundation/2023-04-17-Sales-Pipeline-9c532a01d0834a65ab5728cff163289d
https://www.notion.so/tonomy-foundation/2023-04-11-Meeting-with-Hasheeb-47aff2ae3d584514bfc9049e49c23eb3

**Comment by kamitor** [comment]
https://tonomy-foundation.notion.site/2023-04-27-Sales-team-meet-70a6403a92ea4983be0cf772e125bbf5

Meetings to be held directly after standup every day

**Comment by kamitor** [comment]
>> onboard Binla
