### ISSUE TITLE
Switch between apps in ecosystem - mockups

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#207]
As a user on a Tonomy App I've signed into
I can easily Find other Tonomy Core Apps, or Tonomy Apps that I have previously used and switch to it
So that I can use the Tonomy Apps easily and don't need to worry about finding apps I previously used

Acceptance criteria

- [ ] mockup for the above story is made
- [ ] feedback received

See how Google does it:
https://www.loom.com/share/800e8aa658a34a53bbeff6c0f8b7f576

**Comment by MilicaSequeira** [comment]
2 possible access points: 
1. Side menu:  https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5443-26443&t=N4k74MmZHRcRhhQx-4
2. Navigation bar- extention on click:  https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5482-26605&t=N4k74MmZHRcRhhQx-4

**Comment by theblockstalk** [comment]
https://www.loom.com/share/ca0808c564644ea190064fc383c31585

**Comment by MilicaSequeira** [comment]
It should be created for: Tonomy Demo, Tonomy SSO, eventually Tonomy Participate, Tonomy DAO...not Tonomy ID, its not a Tonomy App but Tonomy Identity service. And ditch the switcher name, it should be in Apps.

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=405-1339&mode=design&t=TgwdJ8KTiBZDg5dh-4
