### ISSUE TITLE
Tonomy Demo mobile design - sign transaction pages

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#218]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4993-26071&t=6uvsdZlcfbGhRKaM-4

Acceptance criteria:

- [ ] Mobile friendly high-fidelity design exists
- [ ] reviewed by one developer, and feedback integrated

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Home%2FVC%2FMSG%2FTX?type=design&node-id=0-11727&t=1XqllowPoZxkSBLO-4
