### ISSUE TITLE
Tonomy ID Demo mobile - sign VC

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#220]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=4877-26077&t=6uvsdZlcfbGhRKaM-4

Acceptance criteria:

- [ ] Mobile friendly high-fidelity design exists
- [ ] reviewed by one developer, and feedback integrated

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=5290%3A26673&t=bb6272vmFK0DXh36-1
