### ISSUE TITLE
Create a list of all the marketing features website needs to have with our pipeline

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#226]
Acceptance criteria

- [ ] create a list of all the conversion mechanisms desired on the website e.g. Twitter feed, and a chatbot

one way to do this would be to adapt the "integrations" we want in the CMS
https://docs.google.com/spreadsheets/d/12r0YJ_WVFGnH4tlsJ10rpTyrcGYgErxp7llex0AzWC0/edit#gid=0

**Comment by kamitor** [comment]
Use the pipeline;  https://app.diagrams.net/#G1gbw-OwG4bZtkDcFwJaE_OisxIN6gggnD
Using this movie:  https://www.youtube.com/watch?v=yxbV-Gvnn5g
Create a diagram how it fits in, and could connect together.

**Comment by kamitor** [comment]
A list to evaluate CSM systems; How to evaluate CSM system.

**Comment by kamitor** [comment]
https://docs.google.com/spreadsheets/d/12r0YJ_WVFGnH4tlsJ10rpTyrcGYgErxp7llex0AzWC0/edit#gid=0

**Comment by kamitor** [comment]
Add which intergrations are actually nesseairy so that we can evaluate better.

**Comment by kamitor** [comment]
Adapt the sheet to be relevant for the website too
