### ISSUE TITLE
Reevaluate Hubspot CMS against the CMS integrations desired features

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#227]
Acceptance criteria

- [ ] For Hubspot CMS option, go through the marketing checklist and document how easy it will be to add that feature to the website

previous work
https://github.com/Tonomy-Foundation/Tonomy-ID-Management/issues/181

**Comment by kamitor** [comment]
Expand this: https://docs.google.com/spreadsheets/d/12r0YJ_WVFGnH4tlsJ10rpTyrcGYgErxp7llex0AzWC0/edit#gid=0
