### ISSUE TITLE
Outreach to new potential client (sprint starting 25 april)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#229]
These are people that we have connected with AND that are intrested;
Only those will be added to the CRM. Not just everyone. 

- [ ] Reach out to these businesses. 25 personalized outreaches made. PERSONALISED
- [ ] document you reach out to, when and what in the CRM

**Comment by kamitor** [comment]
Open - IT

**Comment by kamitor** [comment]
WonderBit

**Comment by Samin261** [comment]
hello test

**Comment by kamitor** [comment]
https://www.notion.so/tonomy-foundation/2023-05-09-Ukraine-Event-c3626591492648a4addc35423800d32f?pvs=4
