### ISSUE TITLE
Arthur / EH3 contact follow up

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#23]
The aim of this task is to make sure we fall up with Arthur, with the opportunity to do some work to integrate EH3 verification into Tonomy ID
https://www.eherkenning.nl/nl/leveranciersoverzicht

Definition of done

- [x] follow up with them, pitch to them - what Tonomy ID and SSI would mean for them / EH3
- [x] see if we can pitch with their partners
- [x] Take notes for any meetings

**Comment by theblockstalk** [comment]
analyse the flows and see what we can do

**Comment by kamitor** [comment]
Planned coming monday
