### ISSUE TITLE
Design Demo site for when user logs out or cancels logs in - research

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#231]
As a user
I can cancel the login or logout of Tonomy ID (either in the Login website, or in Tonomy ID)
So that I can cancel login, or logout

Acceptance criteria:

- [ ] Research a few apps and how they handle this

**Comment by MilicaSequeira** [comment]
Logout rules to follow:
https://usabilitygeek.com/ux-logout-lapse/

UI:
https://gluu.org/docs/de/operation/custom-oxtrust/

https://www.pinterest.fr/pin/pingl-par-thacher-hussain-sur-login-logout--540783867750370916/

https://www.pinterest.fr/pin/540783867750370907/

https://dribbble.com/shots/13893370-Log-out-page

https://dribbble.com/shots/6046169-Logout

https://mobbin.com/screens/3a344c0f-98ff-4599-a921-8a78ed29ae3b

https://www.pinterest.fr/pin/399694535668753541/

https://dribbble.com/shots/2984195-Logged-Out

Cancel:
https://www2.microstrategy.com/producthelp/2020/MobileSDK/Content/topics/android/andr_CustomizingLoginScreen.htm

https://github.com/abpframework/abp/issues/4731

https://flutterappdev.com/2019/05/16/a-simple-login-page-made-with-flutter-web/
