### ISSUE TITLE
Design Demo site for when user logs out or cancels logs in - mockups

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#232]
As a user
I can cancel the login or logout of Tonomy ID (either in the Login website, or in Tonomy ID)
So that I can cancel login, or logout

three cases
- User logs out in Tonomy Id
- User logs out in Tonomy login website
- User cancels in Tonomy login website

Acceptance criteria:

- [ ] Create mockups for the design (mobile or desktop)
- [ ] get feedback and iterate the design based on feedback

**Comment by MilicaSequeira** [comment]
https://discord.com/channels/1029385699071381524/1039498641968205834/1109047309192400926

**Comment by MilicaSequeira** [comment]
https://demo.staging.tonomy.foundation/

**Comment by MilicaSequeira** [comment]
to view the screens, zoom out and only view content in the blue and pink border: 
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=267-3093&t=kIdRp9XdkPd4phP5-4

**Comment by theblockstalk** [comment]
it seems that the three cases are missing
- User logs out in Tonomy Id
- User logs out in Tonomy login website
- User cancels in Tonomy login website

In the above cases the user gets redirected back to the demo site and notification is shown to the user e.g. "You logged out". You can see this https://demo.staging.tonomy.foundation and I think this is where we need new design

The designs you have provided are also useful, But show the following cases instead:
- User logs out of Tonomy Demo
- User logs out of SSO confirmation ( but not the flow after this showing the message shown on the demo site)

**Comment by MilicaSequeira** [comment]
cancels on tonomy ID ( during market.com wait)

**Comment by MilicaSequeira** [comment]
Can I have a review please. Zoom out to see all the screens https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=349-1044&t=r7gEJEDq8JtS6eyi-4

**Comment by MilicaSequeira** [comment]
Please zoom out for the web version: https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=349-1044&t=OhWyVu4ZLmvB9dYA-4

Please zoom out for the mobile version: https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=390-1120&t=OhWyVu4ZLmvB9dYA-4
