### ISSUE TITLE
Screenshot the process of completing the EH3 flow

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#24]
The aim of this task is to understand the technical and non-functional requirements for the EH identity verification flow

Definition of done:

- [x] someone completes one of these, and screenshots OR VIDEO the whole process https://eherkenning.nl/en/list-of-suppliers

**Comment by Carrie22022** [comment]
Here is the video process. 

**Part 1**
https://www.loom.com/share/b08603e481a34d7596af86f6b8f2ba79

**Part 2**
https://www.loom.com/share/27914d8df3b74ea088bf923375de35de

**Part 2 again, if it messed up before**
https://www.loom.com/share/2e38aae741724ac08515ca075c62fa25
