### ISSUE TITLE
Add SCRUM presentation slides to Google Drive

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#242]
Acceptance criteria

- [ ] all workshop presentation slides are uploaded to Google Drive as Google Slides here
https://drive.google.com/drive/folders/1rYhanDdslksJAFQ2ljXG92M2YH4_T2r7

**Comment by chetanabhardwaj** [comment]
Here is the link of the Scrum Presentation.
https://docs.google.com/presentation/d/1E5yXq9UO0ujds2cYN0FI_Gc7DS2RuKWgsaUMz9G6bq8/edit?usp=sharing
