### ISSUE TITLE
Setup a SCRUM working agreement

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#243]
Acceptance criteria

- [ ] setup a working agreement for our SCRUM team
- meeting times and who should attend
- expectations for task reviews
- who controls tasks and when
- links to the DOR/DOD
- [ ] have a meeting where we agree on the contents of the agreement
- [ ] uploaded to Google Drive as a Google Doc or it is Notion

**Comment by chetanabhardwaj** [comment]
Here is the link to the working agreement.
https://docs.google.com/presentation/d/1h4rjvaRRkbBcQxWu6z8WL8u0jqHwiaG6ClGkLF17mZc/edit?usp=sharing
