### ISSUE TITLE
Acceptance criteria testing: SSO login on external website functional testing

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#251]
See if you can break the SSO feature!

Acceptance criteria

- [ ] Test all the acceptance criteria in this epic https://app.zenhub.com/workspaces/tonomy-id-62a06b705d27820023023630/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTA2Nzcy?issueType=issue
- [ ] Try and see if there are other edge cases you can get to as well
- [ ] Follow the testing and reporting guide for reporting bugs https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446

**Comment by theblockstalk** [comment]
note this functional task is still not completed
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/705

also note that the 2fa / MFA features were removed. So do not expect those behaviours (fingerprint / pin)

**Comment by vemakoti** [comment]
update by end of the day 06/06 : Started testing on staging environment. Tested basic scenarios like : user is not logged into the Tonomy ID website, scan QR code from mobile, etc. So far it looks good and working.

One cosmetic defect on  https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446
Link to " Test out the sign in flows on the Login Demo Website:" is pointing to " https://tonomy-id-staging.tonomy.foundation" which is " 404: NOT_FOUND " 

Is " https://demo.staging.tonomy.foundation/ " the correct url? @theblockstalk ?

**Comment by theblockstalk** [comment]
you are correct @vemakoti . I have updated the document

**Comment by vemakoti** [comment]
Update by end of 8th June : Found a bug which is combination of mobile and web.
https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/104

**Comment by vemakoti** [comment]
Update by end of 15th June: Found a bug on SSO login.
https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/109
