### ISSUE TITLE
Design: Low fidelity iteration 1 demo Home Page and VC Page

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID-Management#255]
build a new low fidelity design for the DEMO home page and DEMO VC Page.

Acceptance criteria:

- [ ] few different options showing based on feedback
- [ ] less tech more user friendly
- [ ] feedback from product owner
- [ ]  2 feedback from BD team (preferable Chris and Samin) 

HINTS:
1. less text, more graphics
2. remove explanations
3. remove unnecessary steps to show technical steps
4. make it about the apps not the technical features 
5. "you are now logged in" to more of a user icon
6. code snippets to be optional expandible (hidden in someway)
7. use a stepper to show the steps of the VC signing

**Comment by MilicaSequeira** [comment]
VERSION 1:
Login Home page:
WEB:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=0-1430&t=GayEjGb1GpoMTUq2-4

MOBILE:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=229-911&t=GayEjGb1GpoMTUq2-4

User Home page:
WEB:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=189-944&t=GayEjGb1GpoMTUq2-4

MOBILE:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=229-973&t=GayEjGb1GpoMTUq2-4

VC:
WEB:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=204-1090&t=GayEjGb1GpoMTUq2-4

MOBILE:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=230-916&t=GayEjGb1GpoMTUq2-4

VERSION 2:
Login Home page:
WEB:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-2616&t=GayEjGb1GpoMTUq2-4

MOBILE:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-2686&t=GayEjGb1GpoMTUq2-4

User Home page:
WEB:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-2547&t=GayEjGb1GpoMTUq2-4

MOBILE:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-2645&t=GayEjGb1GpoMTUq2-4

VC:
WEB:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-2183&t=GayEjGb1GpoMTUq2-4

MOBILE:
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-1575&t=GayEjGb1GpoMTUq2-4

**Comment by MilicaSequeira** [comment]
Feedback from Chris and Samin:

-positive improvement on UI

-maybe a simplified version of Tonomy ID login eg. Netflix 

-make it apparent that ur data is safe and private (constant reminder)

-make a gif after login to give a reminder ur secure ( value proposition more clear) 

-human verifying doc is good in a visual sense and simple and clear for nontechy people

-instead of sign a transaction- say heres a usecase of signing a transaction

-make a story before you get to sign a document ( youre at a doctor’s office bla bla storytelling… this doc wants access to your file do you aprove…)

**Comment by theblockstalk** [comment]
my feedback:
https://discord.com/channels/1029385699071381524/1039498641968205834/1111259366419607614

**Comment by MilicaSequeira** [comment]
If i could get a review on 255: Please scroll to right for the rest of the screens: TX) https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=292-1155&t=WJJK7Pqivu6p989R-4 HOME SCREEN NOT SIGNED IN:  https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-2616&t=WJJK7Pqivu6p989R-4 SIGNED IN: https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=232-2547&t=WJJK7Pqivu6p989R-4

**Comment by MilicaSequeira** [comment]
Review of Jack https://www.loom.com/share/3131282bd532480a865a7311eea3ca6b

**Comment by theblockstalk** [comment]
Approved. See comments in the figure files for ideas for the high fidelity
