### ISSUE TITLE
DESIGN: finish low fidelity iteration DEMO sign transaction page

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID-Management#256]
finish low fidelity iteration DEMO sign transaction page

Acceptance Criteria:

- [ ] low fidelity design of the sign transaction page
- [ ] less tech more user friendly
- [ ] feedback from product owner
- [ ] feedback from Samin and Chris

**Comment by MilicaSequeira** [comment]
Screen 1 then scroll to right  for the rest of them: https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=0-2142&t=MCiucVfi0meaeYuP-4

**Comment by theblockstalk** [comment]
reviewed

**Comment by MilicaSequeira** [comment]
Same for task no 256 (scroll to right):  https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=336-1423&t=WJJK7Pqivu6p989R-4

**Comment by MilicaSequeira** [comment]
Review of Jack https://www.loom.com/share/3131282bd532480a865a7311eea3ca6b

**Comment by theblockstalk** [comment]
was expecting something more like this
![image.png](https://images.zenhubusercontent.com/5ea82b5959354f2b8ef14f5d/9e4c3b01-69d4-4f6d-a841-557a646fadca)

**Comment by theblockstalk** [comment]
see comments. approved
