### ISSUE TITLE
High fidelity design iteration 2 DEMO site

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID-Management#257]
build a high fidelity design of the DEMO site based on the low fidelity designs.

acceptance Criteria:
- [ ] HOME page designed
- [ ] VC page designed
- [ ] Sign transactions page designed
- [ ] feedback from product owner 
- [ ] feedback from Samin and Chris (optional)

**Comment by theblockstalk** [comment]
1 points to previous sprint
2 to new sprint

**Comment by MilicaSequeira** [comment]
Version 1: https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=536-3615&t=2AWhxC2BqJO6vhhy-4
Version 2: https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=533-2643&t=2AWhxC2BqJO6vhhy-4

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=610-4288&mode=design&t=C6Nl8CBT23o6pqs6-4
