### ISSUE TITLE
Tonomy SSO - user home page - Low fidelity

### ISSUE THREAD

**Issue by MilicaSequeira** [Tonomy-Foundation/Tonomy-ID-Management#276]
The Tonomy SSO user home page, after the User has logged in.

Create low fidelity versions of the SSO user home page.

Acceptance criteria:

- [ ]  few different options showing based on feedback
- [ ] feedback received

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/Enit7SHcGKiYULpi51Hg36/Accounts-website?type=design&node-id=61-323&mode=design&t=I9Kkl0M8QUiiqes8-4

**Comment by theblockstalk** [comment]
previous sprint: 2
new sprint: 1

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/Enit7SHcGKiYULpi51Hg36/Accounts-website?type=design&node-id=83-75&mode=design&t=ntdoBdvEnrJa8Epp-4
