### ISSUE TITLE
Testing of the demo flows

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#283]
Acceptance criteria

- [ ] a user can login to the Demo website, and sign and validate a medical record
- [ ] a user can login to the Demo website, and send a bank transfer
- [ ] Check that the Demo site works as you would expect it

https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446

**Comment by theblockstalk** [comment]
https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyiddemo

What we can currently test:

- user can create account in Tonomy ID - Demo
- user can logout and log back in
- test create account / login username/password validation
- user can login to https://demo.demo.tonomy.foundation
- can cancel/logout during login to demo
- after login you are on a page in the demo website
- can logout of the demo website

**Comment by vemakoti** [comment]
created following bugs
https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/125
https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/126

**Comment by vemakoti** [comment]
@theblockstalk, After logging into the app, I see that none of the settings are not working. Is this out of scope for testing

**Comment by theblockstalk** [comment]
that is correct. Only logout works currently
