### ISSUE TITLE
Value proposition - web 3

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#29]
The aim of this task is to create a value proposition for web3 companies with an easy to understand story for marketing and sales

Definition of done

- [x] Create the value proposition for Tonmy ID
- [x] produce a small digestible written story that can be used for marketing and sales

**Comment by kamitor** [comment]
https://docs.google.com/document/d/1vTM-wqbC_K5S-aKyw8VmIpDb0jUeszRJMZcYTHTX_i8/edit?usp=sharing
