### ISSUE TITLE
White paper - graphics / beautiful

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#293]
Acceptance criteria

- [ ] add graphics and styling to make the white paper as appealing to technical readers As possible

https://www.canva.com/design/DAFnktNOWKU/24Tn0dFregT2oK7DnCNiFg/edit

**Comment by MilicaSequeira** [comment]
In the first several dozen screens the links were lost. Please check and relink. I would but I have no clue with what were they linked. Sorry.

**Comment by MilicaSequeira** [comment]
Fx needed on 22, 39, 45
