### ISSUE TITLE
Value proposition - cybersecurity and privacy compliance

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#31]
The aim of this task is to create a value proposition for the cybersecurity and privacy compliance use case with an easy to understand story for marketing and sales

Definition of done

- [x] Create the value proposition for Tonmy ID
- [ ] produce a small digestible written story that can be used for marketing and sales

**Comment by kamitor** [comment]
https://noteshare.space/note/cldk7s1d5631901pja2y8apdo#xHA18dkqxs9W0Vcds1iP5bUucRQPvcDbFAu1ZsHyh48

**Comment by kamitor** [comment]
https://noteshare.space/note/cldk7wz2z633401pj3wvbxew5#+lTqaOOK4/i2HEclKHc9Zq+oanjvfP7VgmT1MENyH6A
