### ISSUE TITLE
Email recovery: High fidelity design and feedback

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#312]
Acceptance criteria:

- [ ] design for email recovery created
- [ ] write/design the email the user will receive to recover their account
- [ ] reviewed by PO + 1 other stakeholder

Flows
1. register email (for recovery)
2. recovery with email

**Comment by MilicaSequeira** [comment]
add email when create account plus get otp to verify and when you forgot your passward (click link) then you get another passward.

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5964-29063&mode=design&t=fBFw7cMySkuCMJAk-4

**Comment by theblockstalk** [comment]
this is missing the recovery steps. will discuss during the week

**Comment by theblockstalk** [comment]
Recovery steps:
1. we have sent an email to j****@gmail.com, please enter the verification code we sent there
2. choose new passphrase
3. repeat passphrase

**Comment by theblockstalk** [comment]
previous sprint: 1
new sprint: 1
