### ISSUE TITLE
Try to break Tonomy ID - report errors

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#314]
Acceptance criteria

- [ ] Try using all features of Tonomy ID, in different combinations, orders, devices... report any bugs

Conditions to consider (not exhaustive)

- device: iOS or android
- phone model: e.g. Samsung S40, iPhone 7
- browsers: chrome, firefox...
- user inputs: usernames and password
- features:
  - Tonomy ID: create account, login, logout, SSO
  - Demo features: sign trx, sign VC
- login flows: first time login, login again, logout and login, login, cancels login, logs out during login
- app state during SSO login: open, closed, exited, screen off
- try login with different account
- try pressing buttons as soon as they appear (fast user) or try waiting on screens for a long time (slow user)
- change camera permissions from the OS settings
- user changes the URL (copies, or edits), or tries to go to other inaccessible pages

**Comment by vemakoti** [comment]
Created following defects
https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/134
https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/133
