### ISSUE TITLE
Design screens for passphrase use

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#315]
Acceptance criteria
- [x] design a flow for generating passphrases and additional information needed for the user to understand the reasoning behind passphrase usage 
- [x] BD review point

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5878-28906&mode=design&t=olLN1FbBakfAFiJ7-4

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5878-28906&mode=design&t=olLN1FbBakfAFiJ7-4

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5878-28906&mode=design&t=VyPyNj05KtVTxQ3T-4

**Comment by MilicaSequeira** [comment]
Meeting with 2 members of the BD team (Shayan, Binla) happened on 25.7. 2023. They have approved the design with no additional changes needed.

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5974-29692&mode=design&t=PzrUzpyzbDZaFouE-4
