### ISSUE TITLE
Overview of T&Cs and privacy notice: mockup

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#316]
As a new Tonomy ID user creating an account
I get a 1-page very easy summary of the most important points of the T&Cs
so that I can easily Decide whether to accept them

As a new Tonomy ID user creating an account
I get a 1-page very easy summary of the most important points of the Privacy Notice (Including that we do not store or process any personal information)
so that I can easily Decide whether to accept them

As a new Tonomy ID user creating an account
I Can into marketing emails, and into sharing analytical data (separately) and am told what this data is used for
So that I can make the decision myself and opted

As a Tonomy lawyer
I want to know that all Tonomy ID users explicitly accept Privacy Notice and T&C (opt-in)
So that we know they accepted legal terms

Acceptance criteria:
- [ ] mockup of the new design is created

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=6223-3038&mode=design&t=ry6TG0RIrK2up7le-4
