### ISSUE TITLE
Design transaction sign animation v3: high fidelity design

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#319]
Acceptance criteria:

- [ ] high fidelity design complete
- [ ] 2x BD review and approve

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=609-2256&mode=design&t=y75xYCTAZbsbfmkr-4
