### ISSUE TITLE
Research how other companies do security testing

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#322]
Acceptance criteria

- [x] research how other companies do security testing
- [x] what are the different strategies and what are
  - the pros and cons of each
  - how much work and €€ different strategies have (generally)
  - at what stage of new product development are they good for
  - how much-perceived value do different strategies have
- [x] small summary

Hints:
- things we want to test (https://docs.tonomy.foundation/welcome/requirements)
  - Tonomy ID
  - SDK (business logic library that runs client side)
  - cryptography / authorization system
  - smart contracts (Antelope)
  - communication server
  - accounts website

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/eKGwD6BStwP6NgmxDF3aGX/Security-testing-research?type=whiteboard&node-id=0%3A1&t=AK9LYTFhc2L7YCf2-1

**Comment by theblockstalk** [comment]
https://docs.google.com/document/d/1oZMaScwdNieoRy1N8XqfhnG2QZ2JxrVhHTTjaBp3SYM/edit
