### ISSUE TITLE
Create a list of security testing options so we can choose one or more automated or manual solutions

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#323]
Acceptance criteria:

- [ ] create a list of different security testing options so we can choose one or more automated or manual solutions
- [ ] for each option, provide
  -  cost
  -  how much time it will take
  -  how much work does it require from our technical team
  -  what it provides
 
Hints:
- things we want to test (https://docs.tonomy.foundation/welcome/requirements)
  - Tonomy ID
  - SDK (business logic library that runs client side)
  - cryptography / authorization system
  - smart contracts (Antelope)
  - communication server
  - accounts website

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/eKGwD6BStwP6NgmxDF3aGX/Security-testing-research?type=whiteboard&node-id=23%3A1748&t=gyeMGhHwSJtG0UnM-1
