### ISSUE TITLE
tonomy.io website - UI/UX review

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#324]
Acceptance criteria

- [ ] review UI/UX of website
- [ ] list out fixes

**Comment by MilicaSequeira** [comment]
I will not continue with the review ( done the home page only) until I get a go-ahead if you think this is needed and that it will improve the design. ( Some things I changed so compare to the original and some I just commented on)
https://www.figma.com/file/qR88VrXLC5g7Q0Gd9q6yby/Review-of-Tonomy.io?type=design&node-id=0%3A1&mode=design&t=f4LjN7DAk9R9zyQs-1
