### ISSUE TITLE
tonomy.io website: industry landing pages

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#326]
Acceptance criteria

- [ ] create A set of landing pages explaining 3 different use cases for Tonomy ID
- [ ] add a small summary to the home page and a link to each of them

**Comment by theblockstalk** [comment]
industries:
- [x] banks / finance
- [ ] building access management
- [x] blockchain games
- [ ] web2 / platforms / SaaS
- [ ] web3
- [ ] ssi
- [ ] legal
- [ ] ticketing and events
- [ ] manufacturing
- [ ] tourism?
- [ ] medical
- [ ] energy / power
- [ ] luxury / fashion
- [ ] ecomerce
- [ ] supply chain or logistics
- [ ] education
- [ ] workforce
- [ ] identity and access manager
- [ ] municipality / government
- [ ] corporate management
- [ ] insuracnce
- [ ] government

**Comment by theblockstalk** [comment]
https://discord.com/channels/1029385699071381524/1047429652383277076/1136582279125287012

**Comment by TFariq** [comment]
Use Case Landing Page for the Healthcare Industry Draft
Link:
https://docs.google.com/document/d/1He2jkBvFY5ekoeTREjPa4pBlTtx8-fk82qQr6DPCBLo/edit?usp=sharing

**Comment by theblockstalk** [comment]
use cases:
- keycards
- phishing prevention
- weak password prevention
- smart contracts / web3
- consent management
- data sharing
- decentralized data storage
- GDPR compliance
- server breach prevention

**Comment by shayansal** [comment]
> industries:
> 
> * [X]  banks / finance
> * [ ]  building access management
> * [X]  blockchain games
> * [ ]  web2 / platforms / SaaS
> * [X]  web3
> * [ ]  ssi
> * [ ]  legal
> * [ ]  ticketing and events
> * [ ]  manufacturing
> * [ ]  tourism?
> * [X]  medical/healthcare
> * [ ]  energy / power
> * [ ]  luxury / fashion
> * [ ]  ecomerce
> * [X]  supply chain or logistics
> * [ ]  education
> * [ ]  workforce
> * [ ]  identity and access manager
> * [ ]  municipality / government
> * [ ]  corporate management
> * [X]  insuracnce
> * [ ]  government

**Comment by theblockstalk** [comment]
https://app.zenhub.com/workspaces/business-development-642187266830f15e16d7099d/issues/zh/112
