### ISSUE TITLE
Prepare the product requirements workshop (Sprint starting 18 July)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#333]
Acceptance criteria

- [ ] Prepare the following Miro board
- [ ] as any potential features that might be interesting to talk about

Copy https://miro.com/app/board/uXjVM2EIpLw=/

**Comment by MilicaSequeira** [comment]
![Screenshot_2.png](https://images.zenhubusercontent.com/6391a6cc0faa24ff1a1a9c95/6c88bdc5-3286-4f11-bb53-d97b9c506025)

Unable to complete the task due to  account constaint ( or me doing smtg wrong).

**Comment by theblockstalk** [comment]
https://miro.com/app/board/uXjVMyWJuxA=/
