### ISSUE TITLE
Social media (sprint starting 25 October)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#34]
Description:

We have to create and post some material on our social just to show that we are alive more or less

Definition of done:

- [x]  Visuals are created
- [x]  Tweets posted
- [x]  Linkedin posted
- [x]  Content social media document is updated
- [ ] Post content on our Discord - > Canva From Chris

**Comment by Mrak1985** [comment]
6 tweets, updated social and 1 linkedIn post https://docs.google.com/spreadsheets/d/1dkINqaA5maMgZjT-dUG40RpP9A6jFyqUor2YCbN7c3k/edit#gid=762749088
