### ISSUE TITLE
Prepare the product requirements workshop (Sprint starting one August)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#342]
Acceptance criteria

- [ ] Prepare the following Miro board
- [ ] as any potential features that might be interesting to talk about

Copy from latest Workshop here https://miro.com/app/dashboard/

**Comment by theblockstalk** [comment]
also to add:
- fix security bugs
- mobile design implemented SSO + Demo
- mobile SSO
- SDK refactor for WallID
- Accounts designs updated
- other edge cases Accounts/SSO
- passphrase
- hCaptcha
- email recovery
- industry use case pages
- data sharing / sovereign storage

**Comment by MilicaSequeira** [comment]
https://miro.com/app/board/uXjVMugsP0Q=/
