### ISSUE TITLE
Overview of T&Cs and privacy notice: high fidelity

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#348]
Acceptance criteria

- [ ] high fidelity of the T&C / Privacy and opt-in screens
- [ ] feedback from BD team integrated

**Comment by MilicaSequeira** [comment]
Please  put this to 1 point. The amount of work wasnt for 2. Thank you!

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=6227-3043&mode=design&t=NE5TGVRX47TJRZPu-4
