### ISSUE TITLE
Prepare the product requirements workshop (Sprint starting 15 August)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#357]
Acceptance criteria

- [ ] Prepare the following Miro board
- [ ] as any potential features that might be interesting to talk about

Copy from latest Workshop here https://miro.com/app/dashboard/

**Comment by sadiabbasi** [comment]
https://miro.com/app/board/uXjVMrdBwIM=/
