### ISSUE TITLE
Task for bonding with other teammates (multiperson) (sprint starting 8 Nov)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#36]
We need to create some bonding in our team.

Work together for an hour. Pair programming or in whatever task you are doing.

Definition of done:

- [x]  Working together was done.
- [x] Put a small message on Rocket Chat (Twitter/Linkedin for +3 points) that you worked together, what you did and what you liked about it

**Comment by kamitor** [comment]
Max, Bas, Dylan, Ibrahim done
