### ISSUE TITLE
WallID design prototype - mockups

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#361]
Acceptance criteria

- [ ] Create mock designs for wallid eCommerce platform

**New user:**
As a user I'm visiting Wallid Checkout to complete my online order. I'm filling my personal data: name, surname, address, email, phone number and credit card number. After filling the data I press buy and order is paid. 

At that moment Sovering Account should be created with phone number as unique identifier. All the work is done in the background and personal data: name, surname, address, email, phone number and credit card number saved in the form of verified credentials. 

**Returning user (no app):**
As a user I'm visiting Wallid Checkout to complete my online order. I'm filling my phone number first. Based on phone number we check, does this user has Sovering account. We sent OTP to the user to login on the back ground to the sovering account. As soon as login is done, Wallid pull all the data from the account to the checkout to feel all the data: name, surname, address, email and credit card number. After filling the data I press buy and order is paid.  

If new address or credit card data was filled, we ad new VC to the account. 

We push users to install Tonomy WL app.

**Returning user (with app):**
As a user I'm visiting Wallid Checkout to complete my online order. I see 3 options:
(1) fill my phone number 
(2) scan QR code
(3) button with deep link (mobile) 

I click button and forwarded to the Tonomy WL app. I grant access to the VC. Wallid pull all the data from the account to the checkout to feel all the data: name, surname, address, email and credit card number. After filling the data I press buy and order is paid.  

If a new address or credit card data was filled, we ad new VC to the account.

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/h3OqLtvOnpZ2CItiDw7vXM/Tonomy-Demos?type=design&node-id=6159-5249&mode=design&t=3fxQ96lQ8qr7dKOK-4
