### ISSUE TITLE
Data sharing consent screen design - research

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#363]
Acceptance criteria

- [ ] Research how other platforms do data sharing consent screens

**Comment by MilicaSequeira** [comment]
https://folio.id/wallet-app/

https://apps.apple.com/fr/app/data-wallet/id1546551969

https://www.apple.com/healthcare/health-records/

https://www.youtube.com/watch?app=desktop&v=lx8F5D9qPQI

https://dribbble.com/shots/4357814-Data-sharing-consent

https://www.smashingmagazine.com/2019/04/privacy-ux-aware-design-framework/
