### ISSUE TITLE
Data sharing consent screen design - mockups

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#364]
Acceptance criteria

- [ ] Create mockups for the consent screens
- [ ] Design integrated from feedback from PO and 2x BD

**Comment by MilicaSequeira** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=6382-3351&mode=design&t=CfxVPE6p2VfdmS0R-4

**Comment by theblockstalk** [comment]
previous sprint: 1
next sprint: 2
