### ISSUE TITLE
Access control for admins of apps - research

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#366]
Acceptance criteria

- [ ] Research how other SSO systems do access control of users
- [ ] Discuss findings with PO and BD

As a  SSO provider I want to know which users have access to which system and what rights they have so that I can make judgement calls on barriers and banns.

Figure out what kinds of functionality operators and app managers want to control their users (e.g. invite, delete, set access permissions...)

**Comment by MilicaSequeira** [comment]
Eco-system level ones:
1.	Amazon Web Services (AWS)
2.	Google Cloud Platform (GCP)
3.	Microsoft Azure
4.	Linode
5.	Vultr
6.	Heroku
7.	IBM Cloud
8.	Oracle Cloud Infrastructure (OCI)
9.	Alibaba Cloud
	

App level ones:
1.	Wild Apricot
2.	MemberClicks
3.	GymMaster
4.	Zen Planner
5.	MemberPlanet
6.	MembershipWorks
7.	MemberLeap
8.	VeryConnect
9.	ClubExpress
10.	Membership Toolkit
	


Elements to take inspiration from:
https://www.pcmag.com/reviews/google-cloud-platform (nice eco-system UI)
https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards (for creating ecosystems)
https://sourceforge.net/software/product/MemberClicks/ (expanded digital ocean)
https://www.drupal.org/docs/contributed-modules/drupal-oauth-oidc-login/wild-apricot-sso-login (membership management)
Digital Oceans mobile member management section is a scrollable web version ( not mobile adjusted)
Potential mobile view of a contact https://gethelp.wildapricot.com/en/articles/47-wildapricot-s-mobile-app-for-admins-android
mobile view of all the parts, but the dashboard is still scrollable to the right https://learn.microsoft.com/en-us/azure/devops/project/navigation/mobile-work?view=azure-devops

Possible actions for app based platform:
•	Administrator side
Add, edit, and delete member profiles; Categorize members into different groups or tiers (member, biller, owner but for Tonomies tiers); Send and receive msgs?
•	Members Side
Update personal information, contact details, and preferences; View membership status; Send and receive msgs?

Possible actions for eco-system based platform:
•	Platform administrator side
Add, verify, and manage users and user profiles; Assign roles and permissions to users and organizations; Handle user authentication and security. Onboard and verify vendors, partners, or service providers; Approve or reject vendor applications. Send and receive msgs?
•	Members Side
Update personal information, contact details, and preferences; View membership status; Send and receive msgs?

**Comment by theblockstalk** [comment]
Great start.

I don't know what you mean "send and receive messages". About how different users receive notifications that they have been invited/edited for their access permissions? this is a question like you to come up with an answer to

I think you should create a list of different user stories, and put them in the priority of what you think is the least we can implement to create a usable administration/access control feature (what would be the MVP of this feature) and what would be extra "good to have" featuress

**Comment by theblockstalk** [comment]
send and receive messages?

Q: do we use the P2P messaging feature for this?
A: No, it requires a Tonomy ecosystem to have a chat app that supports this, so the user can definitely receive a message there. We do not have this yet.
