### ISSUE TITLE
Run Civic Participation tool

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#37]
Definition of done

- [x] civic participation app running on a droplet and can be used externally
- [x] Dummy data added
- [x] IP address routing is fine, no SSL needed

Follow up
- analyse why it goes offline

**Comment by kamitor** [comment]
Tried with Jack again on monday; 

Something wrong with the wasm files;

time invested so far; 13 hours

**Comment by kamitor** [comment]
Need to connect my domain to it

**Comment by theblockstalk** [comment]
http://161.35.246.173:3000
