### ISSUE TITLE
Prepare the product requirements workshop (Sprint starting 12 September)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#383]
Acceptance criteria

- [ ] Prepare the following Miro board
- [ ] as any potential features that might be interesting to talk about

Copy from latest Workshop here https://miro.com/app/dashboard/

**Comment by sadiabbasi** [comment]
https://miro.com/app/board/uXjVMgX7nnE=/?share_link_id=347414255769 @theblockstalk
