### ISSUE TITLE
High-fidelity designs of Data Sharing which show data collection purpose

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#398]
Acceptance criteria

- [ ] High fidelity designs are made
- [ ] PO review and iteration

**Comment by MilicaSequeira** [comment]
https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-sharing/data-sharing-a-code-of-practice/data-sharing-agreements/
