### ISSUE TITLE
Telos UK onboarding - get an antelope chain running locally

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#404]
Acceptance criteria

- [x] create network of 3 Antelope nodes connected to each other

https://docs.eosnetwork.com/docs/latest/node-operation/getting-started/

**Comment by sadiabbasi** [comment]
![image](https://github.com/Tonomy-Foundation/Tonomy-ID-Management/assets/38488513/170194f7-49c7-42f2-a5bd-23892c652e08)
