### ISSUE TITLE
Telos UK onboarding - learn their tech stack

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#405]
Acceptance criteria

- [ ] read the wiki http://wiki.advantapro.com/index.php?title=Main_Page
- [x] go through source repositories:
  - [x] https://gitlab.com/advantaproductions/telos-configs
  - [x] https://gitlab.com/advantaproductions/ansible
  - [x] https://github.com/varilink/telos-eosio
- [x] Get access to communication groups, introduce yourself
- [ ] get access to Hetzner (IaaS) https://robot.hetzner.com/server

https://www.notion.so/tonomy-foundation/Telos-UK-fcbba33dbecc4b949203f124b32c7a4c

**Comment by theblockstalk** [comment]
@sadiabbasi still missing access to wiki

**Comment by sadiabbasi** [comment]
https://monitor.eosuk.io/login 
 get access to Hetzner (IaaS)
needed access for these too.

**Comment by theblockstalk** [comment]
this sprint: 2
next sprint: 1
