### ISSUE TITLE
Testing of the demo flows

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#436]
Acceptance criteria

- [ ] a user can login to the Demo website, and sign and validate a medical record
- [ ] a user can login to the Demo website, and send a bank transfer
- [ ] Check that the Demo site works as you would expect it

Notes:
- https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446
- https://github.com/Tonomy-Foundation/Tonomy-ID-Management/issues/283

**Comment by vemakoti** [comment]
Tested first Acceptance criteria. It works as expected
The second acceptance criteria bank transfer page is not enabled. I will check again later.
Few observations:-   
1) Log in demo app passphrase is secure but not friendly
2) The medical record page background image is stretchy

**Comment by vemakoti** [comment]
Tested second acceptance criteria. it works as expected
