### ISSUE TITLE
Social media content and publish (sprint starting 8 November)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#45]
Description:

We have to create and post some material on our social just to show that we are alive more or less

Definition of done:

- [ ]  Tweets posted
- [ ]  Linkedin posted
- [ ] Discord posted
- [ ]  Content social media document is updated

**Comment by theblockstalk** [comment]
https://docs.google.com/spreadsheets/d/1dkINqaA5maMgZjT-dUG40RpP9A6jFyqUor2YCbN7c3k/edit

**Comment by Carrie22022** [comment]
Spoke with Jack, need consistency plan - suggested: at least one per sprint, but target 2.
