### ISSUE TITLE
Design iteration of the Data sharing flow after external usability tests

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#450]
Acceptance criteria

- [ ] designs updated based on external usability testing

**Comment by marcgallifa** [comment]
Usability Testing Results --> 
https://www.figma.com/file/sgnAkCTZT0FPktYSq8axCb/Usability-Testing-Feedback?type=whiteboard&node-id=47%3A464&t=bXM5ReIBilkItQIF-1
