### ISSUE TITLE
UI/UX testing of the mobile flow

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#459]
Acceptance criteria:

- [ ] Testing the UI/UX during the login flow on mobile. Create a Github issue for any suggested fixes using the bug template and screenshots/screenshare videos.

https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446

**Comment by marcgallifa** [comment]
**UX Testing Feedback:**

-Logout and log back in works fine!

-Profile button doesn’t work

-Scrolls horizontally nicely

-If I want to access via desktop, it leads me to mobile

-Fast login works easily

-We can create a Learn about page for Verifiable Credentials and Antelope Blockchain Protocol, within the same app or within Tonomy, so it feels more professional and secure. External links might seem less secure.
Learn about the W3C Verifiable Credentials —> redirects to youtube video
Learn about Antelope blockchain protocol —> reditects to EOS website 

-Payment on Bx Transaction —> recipient field is too small, hard to press the button
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFB1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9243c9c2949527f011e78ff30b1a1376415d5ce2/IMG_1838.PNG)


-Image vectors are slightly cut
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEh1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72e4d2eecee85cc73033f4e8706476e876a87062/IMG_1834.PNG)

-Lack of text alignment, between Sign All Your Transactions vs Sign All Your Documents. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHJ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92031e4047b8f001d087a8a32acdae398e98a2d4/IMG_1834.PNG)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae72e02d6fbb35857d893f49de8fc7af57a04172/IMG_1835.PNG)



-Once we are done with the Signing documents flow, the button ‘Go Back Home’ should redirect us to the main screen 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG51QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aeb1c3060d41a48e532ec0f8df51f0d0b05069f1/IMG_1837.PNG)
