### ISSUE TITLE
3 min pitch with 4 min demo task

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#46]
This is a quick pitch with a demo that we can send to potential partners that want to integrate

Definition of done

- [x] Three minute pitch about Tonomy ID
- [x] for minutes demo of Tonomy ID with SSO login feature

**Comment by kamitor** [comment]
Setup the pitch in Beautify;  Follow the pitch setup
Tonomy - ID Overall
Try 2 use cases

Record the demo

Fit the demo all together

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFSmUinYXI/RcOGcQ4Zx00FM4btkxAR-Q/edit?utm_content=DAFSmUinYXI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by theblockstalk** [comment]
not finished yet

follow ups:
- review and alignment
- social media megapost
- go on the website?

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFSmUinYXI/RcOGcQ4Zx00FM4btkxAR-Q/edit

**Comment by kamitor** [comment]
need a prototype design flow movie
Need a complete pitch

**Comment by kamitor** [comment]
https://www.videosoftdev.com/free-screen-recorder
