### ISSUE TITLE
White paper: design Tonomy DAO screens of application that we do not have already

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#473]
Acceptance criteria

- [ ] design screens of applications that are part of the white paper solution, so they can be added as "screenshots" in the white paper to make it less abstract

**Comment by marcgallifa** [comment]
@theblockstalk asides of Tonomy ID and Tonomy Dev Console, the other applications are Tonomy Pay and any other one?

**Comment by theblockstalk** [comment]
@marcgallifa Please wait until I draft the application section of the White Paper. At this point I will make requests for what screenshots we need

**Comment by theblockstalk** [comment]
current sprint: 2
next sprint: 3
