### ISSUE TITLE
Communicate with possible Partners

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#5]
We need to establish communication with a potential client. It can be anyone, just presenting our Foundation, sharing ideas, getting feedback

Definition of done

- [ ] Communication was made notes were taken

Points are for each person who does this

**Comment by kamitor** [comment]
Theorectically done with casper, but he's not going to pay so we need a new one.

**Comment by kamitor** [comment]
Listen to Interviews from Mrunal
