### ISSUE TITLE
Update screenshots for app stores with new brand guide for Pangea

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#520]
Acceptance criteria

- [ ] Update this Figma page with the new brand guide and logo. The frames should stay the same size as these are the image dimensions requested for screenshots when creating an app store

https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=5679-26528&mode=design&t=505bT2XyOyVaRiZ0-0

- [ ] Upload these screenshots to the app stores (apple/google)

**Comment by pavel-tonomy** [comment]
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?type=design&node-id=8088%3A8537&mode=design&t=8dG5Hb3flrN9LUzM-1

Screenshots for Appstore and google play
If there any problems, text me and we'll find out how to solve them
