### ISSUE TITLE
Onboard the board to security and key management

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#521]
Acceptance criteria

- [ ] Created that outlines how to sign Pangea transactions
- [ ] outline the security behaviour they need to have and their responsibility

**Comment by sadiabbasi** [comment]
https://docs.google.com/presentation/d/12m0CTQSSFA042waZ01sjiHDhwhd1dBBYgGii_KKH2fI/edit#slide=id.p
