### ISSUE TITLE
Task for bonding with other teammates (multiperson) (Sprint starting 8 November)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#53]
We need to create some bonding in our team.

Work together for an hour. Pair programming or in whatever task you are doing.

Definition of done:

- [ ]  Working together was done.
- [ ] Put a small message on Discord (Twitter/Linkedin for +3 points) that you worked together, what you did and what you liked about it

**Comment by kamitor** [comment]
Chao

**Comment by kamitor** [comment]
Aymen

**Comment by kamitor** [comment]
Robert

**Comment by kamitor** [comment]
Evelin

**Comment by kamitor** [comment]
Stefhano
