### ISSUE TITLE
Pangea Tokenomics graphics

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#541]
Acceptance criteria:

- Review graphics in documents and come up with ideas for new graphics. Then go make them.
- https://docs.google.com/document/d/1wJay_rzTu_b2bRRpDiFXkzSsWDhfXMPM9jeAmpYWYc4/edit

**Comment by pavel-tonomy** [comment]
done
https://www.figma.com/file/ZekbB7S2VgmxjtDdOKdFvU/Pangea-graphic?type=design&node-id=267%3A436&mode=design&t=eSUtR6Ho6pRp86P4-1
