### ISSUE TITLE
Research libraries for signing trx on Ethereum and Hedera

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#544]
https://www.npmjs.com/package/hashconnect
https://github.com/hashgraph/hedera-sdk-js

https://walletconnect.com/
https://www.npmjs.com/package/web3

We want to decide if we should provide a wallet connect experience for developers choosing to use UNITED wallet, or require them to use tho Tonomy SDK

Acceptance criteria:
- [ ] List of pros and cons for the two strategies: using existing wallet standards vs using Tonomy SDK

**Comment by sadiabbasi** [comment]
https://github.com/WalletConnect/web-examples?tab=readme-ov-file
**test dapp url:**
https://react-app.walletconnect.com/
**to send test eth:**
https://www.alchemy.com/faucets/ethereum-sepolia
**wallet connect docs:**
https://docs.walletconnect.com/web3wallet/wallet-usage
**send eth transaction function detail:**
https://docs.metamask.io/wallet/reference/eth_sendtransaction/
**to create web3 account and hard code use this:**
https://docs.web3js.org/guides/wallet/
https://docs.web3js.org/guides/wallet/signing/

**Comment by sadiabbasi** [comment]
**Test implementation of create session and sendTransaction function**
https://github.com/sadiabbasi/Test-Dapp/tree/main/src
