### ISSUE TITLE
Proposal for Hogeschool Utreche

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#55]
Definition of done

- [x] 1-page max proposal for what a student team at this school could do for us
- [x] conditions for their project
- [x] how it moves Tonomy towards its mission
- [x] major risks involved and how we mitigate

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFTVxUhGpw/5AoK_2zr-b4qqWXIs2vtng/edit?utm_content=DAFTVxUhGpw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by theblockstalk** [comment]
I do not see any risks anywhere

**Comment by kamitor** [comment]
https://docs.google.com/spreadsheets/d/1jrXKgYlqdzoWE-iBKjXE3b6kzPasDT1wFPKRAR0WUj0/edit
