### ISSUE TITLE
United Citizens Wallet Mobile app is not working on IOS

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-ID-Management#585]
*steps to replicate the issue*

Use these links for United Citizens Wallet
https://pangea.web4.world/united-citizens-wallet  (or)
 

https://apps.apple.com/us/app/united-citizens- wallet/id6482296993
 
Install the United Citizens Wallet app from the App Store

1)Click on "Create Account"
2)Give username then click on "Next"
3)Save the passphrase Click on "Next "
4)Enter the confirmed passphrase Click on "Next"
5)Read the Terms&Conditions then click on "Accept"
6)Check the checkbox on the Terms and Conditions page
7)Click on "Accept "and click on the checkbox on I Am Human 
8)Give a correct image for Captcha on the Human verification page
9)Click on Create an account

*What do you expect to happen?*
After Captcha challenge it should go to the next page.

*What happens*
After the Captcha Challenge page does not go forward

 Your Environment:-
United Citizen Wallet:- Mobile App
Operating system:-ios 17.5.1
United Citizen Wallet version:-2.0.2

**Comment by sadiabbasi** [comment]
ios: 17.5.1
Madhuri can replicate this when creating account after hcaptcha white screen happened..

ME and jekin not able to replicate it in any environment in same 17.5.1 version..

**Comment by sadiabbasi** [comment]
Video shared by madhuri:
https://github.com/user-attachments/assets/464804bc-af02-450f-9487-b8c3ecb3cb56

**Comment by sadiabbasi** [comment]
Video shared by sadia:

https://github.com/user-attachments/assets/8fe185af-35f7-4d08-bbaf-5b5fce62f2ea

**Comment by sadiabbasi** [comment]
Also there is no logs when madhuri tested and get that white screen error.. i checked the communication logs and there is nothing

**Comment by vemakoti** [comment]
I have tested again Today Still am not getting UCW on IOS Version 17.5.1







https://github.com/user-attachments/assets/c65f816a-0288-4170-ab89-e6854b8a0edc


https://github.com/user-attachments/assets/b2704ab1-eb03-45df-b6f0-6f60e17a156a

**Comment by sadiabbasi** [comment]
it's fixed when merge with the latest PR
