### ISSUE TITLE
Usability testing of the VN experience design upgrades

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#589]
not about testing the whole Epic design goals
more about checking the new flows are intuitive and easy

**Comment by pavel-tonomy** [comment]
The script https://docs.google.com/document/d/1CJIBOpv5S4sCNj-kb6eBaKDOX3z9IkCGcc0g86Z3BGw/edit#heading=h.bsm51oey6lud

The results https://docs.google.com/document/d/135GoE2ktOfRtI3ZWNc7SFmfPwTSs04CwJnusWtmZDt8/edit
