### ISSUE TITLE
Existing prospective lead nurturing (sprint starting Dec 22)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#63]
Definition of done

- [x] Nurture existing leads as adequate
- [x] document you reach out to, when and what in the CRM

**Comment by kamitor** [comment]
Fred, 

Ruud,

Adri,

Hogeschool Utrechte

Mark

**Comment by kamitor** [comment]
Amar - blockchain beer

**Comment by kamitor** [comment]
Yolanda Hendriksen

**Comment by kamitor** [comment]
Yolanda Hendriksen

**Comment by kamitor** [comment]
Alfred Pot
