### ISSUE TITLE
Research and outreach to new potential clients (Sprint starting 8 Dec)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#69]
Definition of done

- [x] Research potential businesses that would benefit from using Tonomy ID. If possible, use the use case scenario research.
- [ ] Reach out to these businesses. 5-10 personalized outreaches made. PERSONALISED
- [ ] document you reach out to, when and what in the CRM

**Comment by kamitor** [comment]
Vikas Sukand__ -- COO EX Cola Cola -- contact - Ten Club - https://10club.team/

**Comment by kamitor** [comment]
https://graminschool.org/

**Comment by kamitor** [comment]
https://www.youtube.com/@NeeleshMisra

**Comment by kamitor** [comment]
![image.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/1aecf100-f5e2-49f6-9df5-7b288c0220ba)

**Comment by kamitor** [comment]
![image.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/43c1551f-1ee6-4e28-9fd7-965930c1ba4c)

**Comment by kamitor** [comment]
Society 4.0

**Comment by kamitor** [comment]
Ruud Wijlhuizen

Victor van der hulst
