### ISSUE TITLE
Research how Tonomy ID can assist businesses

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#7]
Check use cases and see what would happen if Tonomy ID was involved instead

Definition of done

- [x] Minimum of three real-life use cases are analysed (e.g. supply chain, medical records, immigration)
- [x] identify where Tonomy ID could/should/would be involved are identified
- [x] Document the pros and cons are identified for the use of Tonomy ID in the use cases

**Comment by kamitor** [comment]
See Value Proposition

**Comment by kamitor** [comment]
Starting again after listening to : https://www.youtube.com/watch?v=Th8JoIan4dg&ab_channel=YCombinator

**Comment by kamitor** [comment]
What is the problem?
