### ISSUE TITLE
Run a EOSIO/Antelope network locally

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#71]
The purpose of this task is to learn how to connect an antelope node together
https://developers.eos.io/manuals/eos/latest/nodeos/index (Eosio < v2.1)
https://docs.eosnetwork.com/leap/latest/nodeos/ (Antelope > v2.0)

Definition of done

- [ ] create a local network on your computer with 2+ blockchain nodes with separate private keys running the blockchain

**Comment by theblockstalk** [comment]
Also to join, for support:
https://t.me/antelopedevs
https://t.me/eosservers
https://t.me/dappstelos
https://discord.gg/eos-network
https://discord.gg/NxJ4xRgg27

Also check if needed
https://github.com/DanailMinchev/awesome-eosio (some resource a bit behind)
https://cc32d9.gitbook.io/antelope-smart-contract-developers-handbook (currently, very up-to-date)
https://github.com/cc32d9/wax-node-instructions

**Comment by Rebal67** [comment]
![Screenshot_20221229_184124.png](https://images.zenhubusercontent.com/62a25073311a1090ffcd4e5f/932e0a46-e46e-4ce3-bfb3-242cd03e0b93)
![Screenshot_20221229_184232.png](https://images.zenhubusercontent.com/62a25073311a1090ffcd4e5f/3a847db0-566b-4eb0-82ce-24757ef2ae18)
