### ISSUE TITLE
Propose a CRM system

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#72]
The idea is too choose a CRM that is suitable for our sales pipeline management. Ideally this will integrate with all our inputs and output stages of the pipeline, website, newsletter, discord even if it makes sense and freshbooks and email

Definition of done

- [ ] Propose three CRM systems with a comparison of their characteristics

Characteristics to consider

- ease of use
- integrations with our (relevant tools):
  - email
  - discord
  - freshbooks
  - social media

- [ ]  3 - 4 options to discuss and the difference between them 
  - Mailchimp
- features
  - email campaigns
  - website form
  - chat bots
  - automation
  - reminders
  - dashboards
  - other features

**Comment by kamitor** [comment]
Testing CiviCrm

**Comment by kamitor** [comment]
docker run -it -p 8080:80 axelor/aio-erp

**Comment by theblockstalk** [comment]
still need to see an overview of top 3 that we can use, including pricing models

**Comment by kamitor** [comment]
Got moved off the board meeting:
I will continue the analysis
Try the top 3
And just make a choice and Implement.

**Comment by theblockstalk** [comment]
https://docs.google.com/spreadsheets/d/12r0YJ_WVFGnH4tlsJ10rpTyrcGYgErxp7llex0AzWC0/edit#gid=0
