### ISSUE TITLE
Telos UK infrastucture access

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#79]
Definition of done

- [ ] Jack
- [ ] Rebal
- [x] Chris

- Have access to all the necessary accounts and infrastructure
https://www.notion.so/tonomy-foundation/Telos-UK-fcbba33dbecc4b949203f124b32c7a4c
- Make sure that it is in the password manager
- Check if the access it there

**Comment by kamitor** [comment]
Setup in Bitvault> ?

**Comment by theblockstalk** [comment]
I'm still waiting for Hetzner access. got everything else
