### ISSUE TITLE
Research and outreach to new potential clients

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#8]
Definition of done

- [x] Research potential businesses that would benefit from using Tonomy ID. If possible, use the use case scenario research.
- [x] Reach out to these businesses. 5-10 personalized outreaches made.
- [ ] document you reach out to, when and what in the CRM

**Comment by kamitor** [comment]
toetreden@eHerkenning.nl

**Comment by kamitor** [comment]
Writing email

**Comment by kamitor** [comment]
https://www.eventbrite.co.uk/e/startup-angel-cafe-startupbootcamp-nxchange-tickets-410422473667

**Comment by kamitor** [comment]
Signing up to event

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/542211562/165a0499-1cbd-41cd-8461-4edb8f6fffe8/download](https://app.zenhub.com/files/542211562/165a0499-1cbd-41cd-8461-4edb8f6fffe8/download)

**Comment by kamitor** [comment]
added jack in case he wants to come. |
Printing tickets for handover tuesday

**Comment by kamitor** [comment]
https://docs.google.com/document/d/1HkUBxOB_Xs5Oeqgv0xlmclVFQFMNPdbcRDI6Ufm-E7w/edit

**Comment by kamitor** [comment]
Setup meeting with Arthur Franse

**Comment by kamitor** [comment]
Setup meeting with Arthur Franse

**Comment by kamitor** [comment]
https://www.linkedin.com/in/roland-van-roermund-9b59a28/
setting up meeting with Roland Van Roermund and 
Cees Jan Ruitenberg https://www.linkedin.com/in/cees-jan-ruitenberg-5894726/ for checking out Tonomy - ID 
And Tonomy - DAO
