### ISSUE TITLE
Telos UK infrastucture deep dive

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#80]
Definition of done

- [x] Jack
- [x] Rebal

- gone through all of the infrastructure and understand what is running their
https://www.notion.so/tonomy-foundation/Telos-UK-fcbba33dbecc4b949203f124b32c7a4c
- document any useful scripts or other kinds of instructions or links to important tools/resources
- A list is created with any tools that can and should be open sourced

Followup Tasks:

- [ ] Onboard the Support help (chris)

**Comment by kamitor** [comment]
Roger and David today - 5'th of Jan - we need to be ready especially if there is a emergency event.

**Comment by theblockstalk** [comment]
most of the following can be open sourced

- http://wiki.advantapro.com/
- https://gitlab.com/advantaproductions/ansible
- https://gitlab.com/advantaproductions/telos-configs

Note direct security sensitive information exists that would allow an attacker to immediately bridge the infrastructure. There is a small amount of security by obscurity used, which should be maintained.

Some sensitive information should be taken out

- IP addresses and domains of hosts (security)
- SSH port (security)
- email addresses and name (privacy)

We could also see in benefits from merging all three of these resources into one open source resource.

There would be challenges in having part of the Ansible playbooks not part of the code base (closed source still), but this could definitely be done.

In making these works open source, we would definitely need to consider how we recognise all of the contributors. Ideally, we could put this on Github and have as much of it is possible associated with their Github accounts.

**Comment by theblockstalk** [comment]
still waiting to checkout Hetzner. all else done
