### ISSUE TITLE
Setup Saleforce CRM - intergrate with sales members

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#91]
DOD:

- [ ] ready for us to use
- [x] Chris, Mike, Jack added
- [ ] Billing setup if needed

Follow ups
-  Gmail accounts and calendars integrated or can be integrated easily
- import existing CRM (maybe good to add to this sprint as well)
- setup automation and templates

As a Sales person of Tonomy ID
I would need materials to send to clients so that I can propose them to connect to us.
So that it will be easy to connect to multipule people at the same time. 

As a Sales person of Tonomy ID
I would need to know which business industries we go for right now, and what the value the would bring to their organisation.
So that I can build marketing and sales pitches that make sense for my target audience 

As a board member of Tonomy Foundation
I need to see clear sales pipelines and costumer contacts 
So that I know how the organisation is doing and what more needs to be done.

- Monitor systems up
- SEO monitoring systems up
- Financial overview system up

As a sales member of Tonomy ID
I need to have an automated CRM pipeline 
So that  it will make making more connections easy and fast.

- CRM SYSTEM enabled
- Linkedin Helper made
- Whatsapp Business intergration
- Demo contract form is up

**Comment by Mrak1985** [comment]
@kamitor I have added the entire system

**Comment by kamitor** [comment]
importing CRM contacts

**Comment by kamitor** [comment]
![Screenshot from 2023-02-24 17-00-44.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/04ef7e91-f135-45c1-8a0d-c8d581d08882)

**Comment by kamitor** [comment]
loaded 2700 contacts into the system.

This system might be too bulky for our needs.  It might be that we need something more simple.

**Comment by kamitor** [comment]
In order to get this system up and running, it will need to be converted and make availble to our needs. 
It might be prudent to try different systems and make sure we can actually set it up BEFORE we try to use it.

**Comment by theblockstalk** [comment]
closing as we are using Hubspot
