### ISSUE TITLE
calculate the $ savings for TID for clients

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#93]
The idea of this task estimates for the average amount that different features of TID will save for our clients

Definition of the

Calculate
- [x] Average $ saved For each user per year due to authorisation secrets hacked
- [x] Average $  saved For each user per year due to Personal information hacked
- [x] Average $  saved For each user per year due to phishing attacks
- [x] Average $  saved For each user per year due to virus's compromising user identity (which are combated by MFA)
- [x] An dutch example is added for each breach. 

Output
- [ ] numbers are communicated to sales and marketing team
- [ ] Add the calculations on the website.

**Comment by kamitor** [comment]
SNAKE START AT SNAKE>??
https://snyk.io/

**Comment by theblockstalk** [comment]
https://ericalexander.org/SecurityBreach/#/

**Comment by Rebal67** [comment]
owasp

**Comment by kamitor** [comment]
https://docs.google.com/spreadsheets/d/137t7LBazUuDogc45s4uB0vZBURW2WCvAjb2BdLkZEzM/edit#gid=0

**Comment by kamitor** [comment]
https://www.canva.com/design/DAFbTtHWg_0/pCdfGOdqDIuULNHc8hcvcw/edit?utm_content=DAFbTtHWg_0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
