### ISSUE TITLE
Nurture existing contacts and leads

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#98]
Definition of done

- [x] Nurture existing leads as adequate
- [x] document you reach out to, when and what in the CRM

**Comment by kamitor** [comment]
Maarten Koningsveld

**Comment by kamitor** [comment]
Fred;

**Comment by kamitor** [comment]
Maarten - WUB; Setup every Tuesday Morning;

**Comment by kamitor** [comment]
Jimmy dunker - Society 4.0 -

**Comment by kamitor** [comment]
(( Chris doesn't find that enough effort has been expended to get the points for this compared to the Other Jobs that have been done ))
